spring.application.name=evaluacion1-desarrolloweb

# Configuración TiDB Cloud
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
logging.level.org.hibernate.SQL=debug
spring.h2.console.enabled=false
spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=39429JNHowU2dKH.root
spring.datasource.password=HVXGQ5w1Lmv9SRRM
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto dinámico para cloud platforms (Koyeb usa $PORT, default 8000)
server.port=${PORT:8000}